apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: "pkt-nats"
  namespace: default
spec:
  autoDeploy: true
  componentType:
    kind: ClusterComponentType
    name: deployment/service
  owner:
    projectName: "doclet-paketo"
