apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: "gcp-frontend"
  namespace: default
spec:
  autoDeploy: true
  componentType:
    kind: ClusterComponentType
    name: deployment/service
  owner:
    projectName: "doclet-gcp"
  workflow:
    kind: ClusterWorkflow
    name: "gcp-buildpacks-builder"
    parameters:
      buildEnv:
        - name: VITE_BASE_PATH
          value: "/gcp-frontend-webapp/"
        - name: VITE_DOC_SERVICE_URL
          value: "http://development-default.openchoreoapis.localhost:19080/gcp-document-api"
        - name: VITE_COLLAB_WS_URL
          value: "ws://development-default.openchoreoapis.localhost:19080/gcp-collab-ws/ws"
      repository:
        appPath: "/project-doclet-app/webapp-react-frontend"
        revision:
          branch: "doclet-gcp-buildpacks"
        url: "https://github.com/Ketharan/sample-workloads"
