apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  labels:
    openchoreo.dev/component: "gcp-postgres"
  name: "gcp-postgres-workload"
  namespace: default
spec:
  container:
    env:
      - key: POSTGRES_USER
        value: doclet
      - key: POSTGRES_PASSWORD
        value: doclet
      - key: POSTGRES_DB
        value: doclet
    image: "postgres:16-alpine"
  endpoints:
    tcp:
      port: 5432
      type: TCP
  owner:
    componentName: "gcp-postgres"
    projectName: "doclet-gcp"
